Repository 47degrees/memeid, pull requests merged in 2020-03, with the labels that each got.

#135 Validate string before calling java.util.fromString
  memeid/src/main/java/memeid/UUID.java
  memeid/src/test/scala/memeid/UUIDSpec.scala
Labels: bug

#136 Compile regex statically in `fromString`
  memeid/src/main/java/memeid/UUID.java
Labels: enhancement

#154 Update actions, documentation templates and configuration files to v0.1.2
  .github/workflows/changelog.yml
  .gitignore
Labels: auto-update

#157 Update actions, documentation templates and configuration files to v0.1.3
  .github/workflows/changelog.yml
Labels: auto-update

#159 Update actions, documentation templates and configuration files to v0.2.2
  .github/workflows/changelog.yml
  .github/workflows/docs.yml
  .github/workflows/scalasteward-auto-approve.yml
  .mergify.yml
Labels: auto-update

#160 Update actions, documentation templates and configuration files to v0.2.3
  .github/workflows/changelog.yml
  .github/workflows/docs.yml
  .github/workflows/scalasteward-auto-approve.yml
Labels: auto-update
